languageCode = "en-us"
title = "Mike Perham"
baseURL = "https://www.mikeperham.com"
theme = "simple-hugo"
relativeURLs = false
publishDir = "docs"
disableKinds = ["section", "taxonomy", "taxonomyTerm"]
pygmentsCodefences = true
pygmentsStyle = "monokai"
rssLimit = 10

[permalinks]
  post = "/:year/:month/:day/:title/"

[params]
  author = "Mike Perham"
  shortDescription = "Ruby, OSS and the Internet"
  email = "mperham@gmail.com"
  github = "mperham"

[blackfriday]
smartypants = false

[params.links]

[params.links.aSidekiq]
"url" = "https://sidekiq.org/"
"title" = "Sidekiq"

[params.links.bFaktory]
"url" = "http://contribsys.com/faktory/"
"title" = "Faktory"

[params.links.cEvents]
"url" = "/events/"
"title" = "Events"

[params.links.dAbout]
"url" = "/about/"
"title" = "About"
